### ISSUE TITLE
project status

### ISSUE THREAD

**Issue by Mehdi-YC** [tranbom/veman#1]
hey sir , gr8 project , i wanted to check if this project is still in developement , 
i recently created a project to acheive the same as this one , the irony is that i'v created it in golang
https://github.com/Mehdi-YC/lazyvenv
and if your project is still alive we can collaborate to make it better , i want a lightweight alternative to conda

**Comment by tranbom** [comment]
Hello!

Yes, the veman project is very much alive! I've been a bit busy with other stuff, hence the lack of activity for a while. 
I will resume development of new features within 1 or 2 weeks.
